name: spray
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4


dependencies:
  flutter:
    sdk: flutter


  animated_switcher_plus: ^1.4.0
  auto_route: ^11.1.0

  badges: ^3.1.2

  device_preview: ^1.3.1
  dropdown_button2:

  flutter_animate: ^4.5.2
  flutter_otp_text_field:
  flutter_riverpod: ^3.2.0
  flutter_staggered_animations:
  flutter_svg: ^2.2.3

  google_fonts: ^8.0.0

  http: ^1.6.0

  iconsax_plus: ^1.0.0
  image_picker:
  intl: ^0.20.1

  lucide_icons_flutter:

  mobile_scanner:

  qr_flutter:

  skeletonizer:


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  auto_route_generator: ^10.4.0
  build_runner: ^2.10.5

flutter:
  uses-material-design: true

  assets:
     - assets/svgs/