name: spray
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4


dependencies:
  flutter:
    sdk: flutter


  http: ^1.6.0
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.2.0
  auto_route: ^11.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  auto_route_generator: ^10.4.0
  build_runner: ^2.10.5

  google_fonts: ^8.0.0

flutter:
  uses-material-design: true
  assets:
     - assets/svgs/